<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-03-02">

<title>Problem set 6</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="pset-06-election_files/libs/clipboard/clipboard.min.js"></script>
<script src="pset-06-election_files/libs/quarto-html/quarto.js"></script>
<script src="pset-06-election_files/libs/quarto-html/popper.min.js"></script>
<script src="pset-06-election_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="pset-06-election_files/libs/quarto-html/anchor.min.js"></script>
<link href="pset-06-election_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="pset-06-election_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="pset-06-election_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="pset-06-election_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="pset-06-election_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Problem set 6</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 2, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>For this problem set we want you to predict the 2024 election. You you will report a prediction of the number of electoral votes for Harris and an interval. You will do the same for the popular vote. You will compare your accuracy to the true results.</p>
<ol type="1">
<li>Read in the data provided here:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/dmcable/BIOSTAT620/refs/heads/main/data/president_polls.csv"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Examine the data frame paying particular attention to the <code>poll_id</code> <code>question_id</code>, <code>population</code>, and <code>candidate</code>. Note that some polls have more than one question based on different population types.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'rvest'

The following object is masked from 'package:readr':

    guess_encoding</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data from provided URL</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/dmcable/BIOSTAT620/refs/heads/main/data/president_polls.csv"</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>raw_dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 18095 Columns: 52
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (25): pollster, sponsors, display_name, pollster_rating_name, methodolog...
dbl (16): poll_id, pollster_id, pollster_rating_id, numeric_grade, pollscore...
num  (1): sponsor_ids
lgl (10): endorsed_candidate_id, endorsed_candidate_name, endorsed_candidate...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check first few rows</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(raw_dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 18,095
Columns: 52
$ poll_id                   &lt;dbl&gt; 89372, 89372, 89372, 89372, 89372, 89372, 89…
$ pollster_id               &lt;dbl&gt; 1528, 1528, 1528, 1528, 1528, 1528, 1528, 15…
$ pollster                  &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "A…
$ sponsor_ids               &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sponsors                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ display_name              &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "A…
$ pollster_rating_id        &lt;dbl&gt; 546, 546, 546, 546, 546, 546, 546, 546, 546,…
$ pollster_rating_name      &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "A…
$ numeric_grade             &lt;dbl&gt; 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7,…
$ pollscore                 &lt;dbl&gt; -0.8, -0.8, -0.8, -0.8, -0.8, -0.8, -0.8, -0…
$ methodology               &lt;chr&gt; "Online Ad", "Online Ad", "Online Ad", "Onli…
$ transparency_score        &lt;dbl&gt; 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,…
$ state                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, "Arizona", "Ariz…
$ start_date                &lt;chr&gt; "11/3/24", "11/3/24", "11/3/24", "11/3/24", …
$ end_date                  &lt;chr&gt; "11/4/24", "11/4/24", "11/4/24", "11/4/24", …
$ sponsor_candidate_id      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sponsor_candidate         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sponsor_candidate_party   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ endorsed_candidate_id     &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ endorsed_candidate_name   &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ endorsed_candidate_party  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ question_id               &lt;dbl&gt; 216453, 216453, 216453, 216453, 216453, 2164…
$ sample_size               &lt;dbl&gt; 2703, 2703, 2703, 2703, 2703, 2703, 2703, 87…
$ population                &lt;chr&gt; "lv", "lv", "lv", "lv", "lv", "lv", "lv", "l…
$ subpopulation             &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ population_full           &lt;chr&gt; "lv", "lv", "lv", "lv", "lv", "lv", "lv", "l…
$ tracking                  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ created_at                &lt;chr&gt; "11/4/24 19:06", "11/4/24 19:06", "11/4/24 1…
$ notes                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ url                       &lt;chr&gt; "https://atlasintel.org/poll/usa-national-20…
$ url_article               &lt;chr&gt; "https://atlasintel.org/poll/usa-national-20…
$ url_topline               &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ url_crosstab              &lt;chr&gt; "https://cdn.atlasintel.org/f1cec70d-8eae-44…
$ source                    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ internal                  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ partisan                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ race_id                   &lt;dbl&gt; 8914, 8914, 8914, 8914, 8914, 8914, 8914, 87…
$ cycle                     &lt;dbl&gt; 2024, 2024, 2024, 2024, 2024, 2024, 2024, 20…
$ office_type               &lt;chr&gt; "U.S. President", "U.S. President", "U.S. Pr…
$ seat_number               &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ seat_name                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ election_date             &lt;chr&gt; "11/5/24", "11/5/24", "11/5/24", "11/5/24", …
$ stage                     &lt;chr&gt; "general", "general", "general", "general", …
$ nationwide_batch          &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ ranked_choice_reallocated &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ ranked_choice_round       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ hypothetical              &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ party                     &lt;chr&gt; "DEM", "REP", "GRE", "IND", "LIB", "DEM", "R…
$ answer                    &lt;chr&gt; "Harris", "Trump", "Stein", "West", "Oliver"…
$ candidate_id              &lt;dbl&gt; 16661, 16651, 31116, 31097, 31790, 16661, 16…
$ candidate_name            &lt;chr&gt; "Kamala Harris", "Donald Trump", "Jill Stein…
$ pct                       &lt;dbl&gt; 48.1, 49.2, 1.1, 0.3, 0.1, 48.8, 50.0, 45.9,…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>raw_dat <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(candidate_name, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 64 × 2
   candidate_name        n
   &lt;chr&gt;             &lt;int&gt;
 1 Donald Trump       5973
 2 Joe Biden          3883
 3 Kamala Harris      2652
 4 Jill Stein         1379
 5 Robert F. Kennedy  1346
 6 Cornel West         952
 7 Chase Oliver        827
 8 Ron DeSantis        466
 9 Nikki Haley         152
10 Lars Mapstead        59
# ℹ 54 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>raw_dat <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(population, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  population     n
  &lt;chr&gt;      &lt;int&gt;
1 lv          8541
2 rv          8481
3 a           1040
4 v             29
5 &lt;NA&gt;           4</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Polls are based on either likely voters (lv), registered voters (rv), all voters (a), or voters (v). Polls based on ‘voters’ are exit polls. We want to remove these because exit polls are too old or might be biased due to differences in the likelihood of early voter by party. We prefer likely voter (lv) polls because they are more predictive. Registered voter polls are more predictive than all voter (a) polls. Remove the exit poll (v) polls and then redefine <code>population</code> to be a factor ordered from best to worse predictive power: (lv, rv, a). You should also remove hypothetical polls and make the date columns into date objects. Name the resulting data frame <code>dat</code>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> raw_dat <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(population <span class="sc">!=</span> <span class="st">"v"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove hypothetical polls</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>hypothetical) <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert date columns and set population as an ordered factor</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_date =</span> <span class="fu">as.Date</span>(start_date, <span class="at">format =</span> <span class="st">"%m/%d/%y"</span>),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">end_date =</span> <span class="fu">as.Date</span>(end_date, <span class="at">format =</span> <span class="st">"%m/%d/%y"</span>),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">population =</span> <span class="fu">factor</span>(population, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"lv"</span>, <span class="st">"rv"</span>, <span class="st">"a"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,611
Columns: 52
$ poll_id                   &lt;dbl&gt; 89372, 89372, 89372, 89372, 89372, 89372, 89…
$ pollster_id               &lt;dbl&gt; 1528, 1528, 1528, 1528, 1528, 1528, 1528, 15…
$ pollster                  &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "A…
$ sponsor_ids               &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sponsors                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ display_name              &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "A…
$ pollster_rating_id        &lt;dbl&gt; 546, 546, 546, 546, 546, 546, 546, 546, 546,…
$ pollster_rating_name      &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "A…
$ numeric_grade             &lt;dbl&gt; 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7,…
$ pollscore                 &lt;dbl&gt; -0.8, -0.8, -0.8, -0.8, -0.8, -0.8, -0.8, -0…
$ methodology               &lt;chr&gt; "Online Ad", "Online Ad", "Online Ad", "Onli…
$ transparency_score        &lt;dbl&gt; 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,…
$ state                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, "Arizona", "Ariz…
$ start_date                &lt;date&gt; 2024-11-03, 2024-11-03, 2024-11-03, 2024-11…
$ end_date                  &lt;date&gt; 2024-11-04, 2024-11-04, 2024-11-04, 2024-11…
$ sponsor_candidate_id      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sponsor_candidate         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sponsor_candidate_party   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ endorsed_candidate_id     &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ endorsed_candidate_name   &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ endorsed_candidate_party  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ question_id               &lt;dbl&gt; 216453, 216453, 216453, 216453, 216453, 2164…
$ sample_size               &lt;dbl&gt; 2703, 2703, 2703, 2703, 2703, 2703, 2703, 87…
$ population                &lt;ord&gt; lv, lv, lv, lv, lv, lv, lv, lv, lv, lv, lv, …
$ subpopulation             &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ population_full           &lt;chr&gt; "lv", "lv", "lv", "lv", "lv", "lv", "lv", "l…
$ tracking                  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ created_at                &lt;chr&gt; "11/4/24 19:06", "11/4/24 19:06", "11/4/24 1…
$ notes                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ url                       &lt;chr&gt; "https://atlasintel.org/poll/usa-national-20…
$ url_article               &lt;chr&gt; "https://atlasintel.org/poll/usa-national-20…
$ url_topline               &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ url_crosstab              &lt;chr&gt; "https://cdn.atlasintel.org/f1cec70d-8eae-44…
$ source                    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ internal                  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ partisan                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ race_id                   &lt;dbl&gt; 8914, 8914, 8914, 8914, 8914, 8914, 8914, 87…
$ cycle                     &lt;dbl&gt; 2024, 2024, 2024, 2024, 2024, 2024, 2024, 20…
$ office_type               &lt;chr&gt; "U.S. President", "U.S. President", "U.S. Pr…
$ seat_number               &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ seat_name                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ election_date             &lt;chr&gt; "11/5/24", "11/5/24", "11/5/24", "11/5/24", …
$ stage                     &lt;chr&gt; "general", "general", "general", "general", …
$ nationwide_batch          &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ ranked_choice_reallocated &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ ranked_choice_round       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ hypothetical              &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ party                     &lt;chr&gt; "DEM", "REP", "GRE", "IND", "LIB", "DEM", "R…
$ answer                    &lt;chr&gt; "Harris", "Trump", "Stein", "West", "Oliver"…
$ candidate_id              &lt;dbl&gt; 16661, 16651, 31116, 31097, 31790, 16661, 16…
$ candidate_name            &lt;chr&gt; "Kamala Harris", "Donald Trump", "Jill Stein…
$ pct                       &lt;dbl&gt; 48.1, 49.2, 1.1, 0.3, 0.1, 48.8, 50.0, 45.9,…</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Some polls asked more than one questions. So if you filter to one poll ID in our dataset, you might see more than one question ID associated with the same poll. The most common reason for this is that they asked a head-to-head question (Harris versus Trump) and, in the same poll, a question about all candidates. We want to prioritize the head-to-head questions.</li>
</ol>
<p>Add a column that tells us, for each question, how many candidates where mentioned in that question.</p>
<p>Add a new column <code>n</code> to <code>dat</code> that provides the number of candidates mentioned for each question. For example the relevant column of your final table will looks something like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><code>poll_id</code></th>
<th><code>question_id</code></th>
<th><code>candidate</code></th>
<th><code>n</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>Harris</td>
<td>2</td>
</tr>
<tr class="even">
<td>1</td>
<td>1</td>
<td>Trump</td>
<td>2</td>
</tr>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>Harris</td>
<td>3</td>
</tr>
<tr class="even">
<td>1</td>
<td>2</td>
<td>Trump</td>
<td>3</td>
</tr>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>Stein</td>
<td>3</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(poll_id, question_id) <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,611
Columns: 53
$ poll_id                   &lt;dbl&gt; 89372, 89372, 89372, 89372, 89372, 89372, 89…
$ pollster_id               &lt;dbl&gt; 1528, 1528, 1528, 1528, 1528, 1528, 1528, 15…
$ pollster                  &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "A…
$ sponsor_ids               &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sponsors                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ display_name              &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "A…
$ pollster_rating_id        &lt;dbl&gt; 546, 546, 546, 546, 546, 546, 546, 546, 546,…
$ pollster_rating_name      &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "A…
$ numeric_grade             &lt;dbl&gt; 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7,…
$ pollscore                 &lt;dbl&gt; -0.8, -0.8, -0.8, -0.8, -0.8, -0.8, -0.8, -0…
$ methodology               &lt;chr&gt; "Online Ad", "Online Ad", "Online Ad", "Onli…
$ transparency_score        &lt;dbl&gt; 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,…
$ state                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, "Arizona", "Ariz…
$ start_date                &lt;date&gt; 2024-11-03, 2024-11-03, 2024-11-03, 2024-11…
$ end_date                  &lt;date&gt; 2024-11-04, 2024-11-04, 2024-11-04, 2024-11…
$ sponsor_candidate_id      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sponsor_candidate         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sponsor_candidate_party   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ endorsed_candidate_id     &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ endorsed_candidate_name   &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ endorsed_candidate_party  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ question_id               &lt;dbl&gt; 216453, 216453, 216453, 216453, 216453, 2164…
$ sample_size               &lt;dbl&gt; 2703, 2703, 2703, 2703, 2703, 2703, 2703, 87…
$ population                &lt;ord&gt; lv, lv, lv, lv, lv, lv, lv, lv, lv, lv, lv, …
$ subpopulation             &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ population_full           &lt;chr&gt; "lv", "lv", "lv", "lv", "lv", "lv", "lv", "l…
$ tracking                  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ created_at                &lt;chr&gt; "11/4/24 19:06", "11/4/24 19:06", "11/4/24 1…
$ notes                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ url                       &lt;chr&gt; "https://atlasintel.org/poll/usa-national-20…
$ url_article               &lt;chr&gt; "https://atlasintel.org/poll/usa-national-20…
$ url_topline               &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ url_crosstab              &lt;chr&gt; "https://cdn.atlasintel.org/f1cec70d-8eae-44…
$ source                    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ internal                  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ partisan                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ race_id                   &lt;dbl&gt; 8914, 8914, 8914, 8914, 8914, 8914, 8914, 87…
$ cycle                     &lt;dbl&gt; 2024, 2024, 2024, 2024, 2024, 2024, 2024, 20…
$ office_type               &lt;chr&gt; "U.S. President", "U.S. President", "U.S. Pr…
$ seat_number               &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ seat_name                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ election_date             &lt;chr&gt; "11/5/24", "11/5/24", "11/5/24", "11/5/24", …
$ stage                     &lt;chr&gt; "general", "general", "general", "general", …
$ nationwide_batch          &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ ranked_choice_reallocated &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ ranked_choice_round       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ hypothetical              &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ party                     &lt;chr&gt; "DEM", "REP", "GRE", "IND", "LIB", "DEM", "R…
$ answer                    &lt;chr&gt; "Harris", "Trump", "Stein", "West", "Oliver"…
$ candidate_id              &lt;dbl&gt; 16661, 16651, 31116, 31097, 31790, 16661, 16…
$ candidate_name            &lt;chr&gt; "Kamala Harris", "Donald Trump", "Jill Stein…
$ pct                       &lt;dbl&gt; 48.1, 49.2, 1.1, 0.3, 0.1, 48.8, 50.0, 45.9,…
$ n                         &lt;int&gt; 5, 5, 5, 5, 5, 2, 2, 4, 4, 4, 4, 2, 2, 4, 4,…</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>We are going to focus on the Harris versus Trump comparison. Redefine <code>dat</code> to only include the rows providing information for Harris and Trump. Then pivot the dataset so that the percentages for Harris and Trump are in their own columns. Note that for pivot to work you will have to remove some columns. To avoid this keep only the columns you are pivoting and along with <code>poll_id</code>, <code>question_id</code>, <code>state</code>, <code>pollster</code>, <code>start_date</code>, <code>end_date</code>, <code>numeric_grade</code>, <code>sample_size</code>. Once you accomplish the pivot, add a column called <code>spread</code> with the difference between Harris and Trump.</li>
</ol>
<p>Note that the values stored in <code>spread</code> are estimates of the popular vote difference that we will use to predict:</p>
<p><strong>spread = % of the popular vote for Harris - % of the popular vote for Trump</strong></p>
<p>However, for the calculations in the rest of problem set to be consistent with the sampling model we have been discussing in class, save <code>spread</code> as a proportion, not a percentage. But remember to turn it back to a percentage when reporting your answer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(candidate_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Kamala Harris"</span>, <span class="st">"Donald Trump"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Select relevant columns</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    poll_id, question_id, state, pollster, start_date, end_date, </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    numeric_grade, sample_size, population, candidate_name, pct, n</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert candidate names into separate columns</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> candidate_name, <span class="at">values_from =</span> pct) <span class="sc">%&gt;%</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Compute the spread (percentage point difference between Harris and Trump)</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">spread =</span> (<span class="st">`</span><span class="at">Kamala Harris</span><span class="st">`</span> <span class="sc">-</span> <span class="st">`</span><span class="at">Donald Trump</span><span class="st">`</span>) <span class="sc">/</span> <span class="dv">100</span>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,189
Columns: 13
$ poll_id         &lt;dbl&gt; 89372, 89372, 89373, 89373, 89374, 89374, 89375, 89375…
$ question_id     &lt;dbl&gt; 216453, 216454, 216464, 216465, 216466, 216467, 216468…
$ state           &lt;chr&gt; NA, NA, "Arizona", "Arizona", "Georgia", "Georgia", "M…
$ pollster        &lt;chr&gt; "AtlasIntel", "AtlasIntel", "AtlasIntel", "AtlasIntel"…
$ start_date      &lt;date&gt; 2024-11-03, 2024-11-03, 2024-11-03, 2024-11-03, 2024-…
$ end_date        &lt;date&gt; 2024-11-04, 2024-11-04, 2024-11-04, 2024-11-04, 2024-…
$ numeric_grade   &lt;dbl&gt; 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7,…
$ sample_size     &lt;dbl&gt; 2703, 2703, 875, 875, 1112, 1112, 1113, 1113, 707, 707…
$ population      &lt;ord&gt; lv, lv, lv, lv, lv, lv, lv, lv, lv, lv, lv, lv, lv, lv…
$ n               &lt;int&gt; 5, 2, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 4, …
$ `Kamala Harris` &lt;dbl&gt; 48.10, 48.80, 45.90, 46.50, 48.20, 48.30, 47.80, 48.30…
$ `Donald Trump`  &lt;dbl&gt; 49.20, 50.00, 51.00, 51.60, 48.20, 49.90, 49.60, 49.80…
$ spread          &lt;dbl&gt; -0.011, -0.012, -0.051, -0.051, 0.000, -0.016, -0.018,…</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Note that some polls have multiple questions. We want to keep only one question per poll. We will keep likely voter (lv) polls when available, and prefer register voter (rv) over all voter polls (a). If more than one question was asked in one poll, take the most targeted question (smallest <code>n</code>). Save the resulting table<code>dat</code>. Note that now each after you do this each row will represents exactly one poll/question, so can remove <code>n</code>, <code>poll_id</code> and <code>question_id</code>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="st">"population"</span> <span class="sc">%in%</span> <span class="fu">colnames</span>(dat)) {</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  dat <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(<span class="fu">select</span>(population_dat, poll_id, question_id, population), </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"poll_id"</span>, <span class="st">"question_id"</span>))</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(poll_id, question_id) <span class="sc">|&gt;</span>  </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(poll_id) <span class="sc">|&gt;</span> </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">priority =</span> <span class="fu">case_when</span>(</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    population <span class="sc">==</span> <span class="st">"lv"</span> <span class="sc">~</span> <span class="dv">1</span>,  </span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    population <span class="sc">==</span> <span class="st">"rv"</span> <span class="sc">~</span> <span class="dv">2</span>,  </span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    population <span class="sc">==</span> <span class="st">"a"</span>  <span class="sc">~</span> <span class="dv">3</span>,  </span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">4</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">|&gt;</span> </span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(priority <span class="sc">==</span> <span class="fu">min</span>(priority, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span>  </span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(question_id <span class="sc">==</span> <span class="fu">min</span>(question_id, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span>  </span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="st">"priority"</span> <span class="sc">%in%</span> <span class="fu">colnames</span>(dat)) {</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  dat <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="sc">-</span>priority)</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,516
Columns: 13
$ poll_id         &lt;dbl&gt; 74819, 74995, 74998, 75491, 76285, 76441, 76752, 76905…
$ question_id     &lt;dbl&gt; 142439, 142927, 142946, 144007, 145354, 145617, 146302…
$ state           &lt;chr&gt; NA, NA, NA, NA, NA, NA, "Florida", NA, NA, NA, NA, NA,…
$ pollster        &lt;chr&gt; "McLaughlin", "Echelon Insights", "McLaughlin", "McLau…
$ start_date      &lt;date&gt; 2021-05-12, 2021-06-18, 2021-06-16, 2021-07-29, 2021-…
$ end_date        &lt;date&gt; 2021-05-18, 2021-06-22, 2021-06-20, 2021-08-03, 2021-…
$ numeric_grade   &lt;dbl&gt; 0.5, 2.7, 0.5, 0.5, 0.5, 2.1, 1.3, 0.5, 1.8, 0.5, 1.5,…
$ sample_size     &lt;dbl&gt; 1000, 1001, 1000, 1000, 1000, 1000, 450, 1000, 1500, 1…
$ population      &lt;ord&gt; lv, rv, lv, lv, lv, lv, lv, lv, rv, lv, rv, lv, lv, lv…
$ n               &lt;int&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
$ `Kamala Harris` &lt;dbl&gt; 45.0, 47.0, 45.0, 46.0, 47.0, 39.0, 50.7, 46.0, 33.0, …
$ `Donald Trump`  &lt;dbl&gt; 49.0, 40.0, 49.0, 49.0, 49.0, 52.0, 49.3, 49.0, 42.0, …
$ spread          &lt;dbl&gt; -0.040, 0.070, -0.040, -0.030, -0.020, -0.130, 0.014, …</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>Separate <code>dat</code> into two data frames: one with popular vote polls and one with state level polls. Call them <code>popular_vote</code> and <code>polls</code> respectively.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>popular_vote <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(state))  </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>polls <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(state))  </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(popular_vote)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 484
Columns: 13
$ poll_id         &lt;dbl&gt; 74819, 74995, 74998, 75491, 76285, 76441, 76905, 77744…
$ question_id     &lt;dbl&gt; 142439, 142927, 142946, 144007, 145354, 145617, 146596…
$ state           &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ pollster        &lt;chr&gt; "McLaughlin", "Echelon Insights", "McLaughlin", "McLau…
$ start_date      &lt;date&gt; 2021-05-12, 2021-06-18, 2021-06-16, 2021-07-29, 2021-…
$ end_date        &lt;date&gt; 2021-05-18, 2021-06-22, 2021-06-20, 2021-08-03, 2021-…
$ numeric_grade   &lt;dbl&gt; 0.5, 2.7, 0.5, 0.5, 0.5, 2.1, 0.5, 1.8, 0.5, 1.5, 1.8,…
$ sample_size     &lt;dbl&gt; 1000, 1001, 1000, 1000, 1000, 1000, 1000, 1500, 1000, …
$ population      &lt;ord&gt; lv, rv, lv, lv, lv, lv, lv, rv, lv, rv, lv, lv, lv, rv…
$ n               &lt;int&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
$ `Kamala Harris` &lt;dbl&gt; 45, 47, 45, 46, 47, 39, 46, 33, 42, 41, 38, 41, 40, 39…
$ `Donald Trump`  &lt;dbl&gt; 49, 40, 49, 49, 49, 52, 49, 42, 50, 50, 42, 41, 51, 49…
$ spread          &lt;dbl&gt; -0.04, 0.07, -0.04, -0.03, -0.02, -0.13, -0.03, -0.09,…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(polls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,032
Columns: 13
$ poll_id         &lt;dbl&gt; 76752, 78084, 80715, 82878, 83215, 84542, 84543, 84544…
$ question_id     &lt;dbl&gt; 146302, 151135, 161813, 173613, 175598, 184809, 184810…
$ state           &lt;chr&gt; "Florida", "New Hampshire", "Florida", "Texas", "New H…
$ pollster        &lt;chr&gt; "Victory Insights", "Trafalgar Group", "Suffolk", "Tex…
$ start_date      &lt;date&gt; 2021-09-16, 2021-12-10, 2022-09-15, 2023-05-08, 2023-…
$ end_date        &lt;date&gt; 2021-09-18, 2021-12-12, 2022-09-18, 2023-05-17, 2023-…
$ numeric_grade   &lt;dbl&gt; 1.3, 0.7, 2.9, NA, NA, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2…
$ sample_size     &lt;dbl&gt; 450, 1041, 500, 1000, 895, 603, 629, 616, 611, 600, 60…
$ population      &lt;ord&gt; lv, lv, lv, rv, lv, lv, lv, lv, lv, lv, lv, rv, lv, rv…
$ n               &lt;int&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
$ `Kamala Harris` &lt;dbl&gt; 50.7, 46.0, 44.4, 39.0, NA, 43.0, 44.0, 48.0, 42.0, 44…
$ `Donald Trump`  &lt;dbl&gt; 49.3, 47.8, 45.6, 46.0, 32.9, 48.0, 47.0, 46.0, 50.0, …
$ spread          &lt;dbl&gt; 0.014, -0.018, -0.012, -0.070, NA, -0.050, -0.030, 0.0…</code></pre>
</div>
</div>
<ol start="7" type="1">
<li>For the popular vote, plot the spread reported by each poll against start date for polls starting after July 21, 2024. Rename all the pollsters with less than 5 polls during this period as <code>Other</code>. Use color to denote pollster. Make separate plots for likely voters and registered voters. Do not use <em>all voter</em> polls (a). Use <code>geom_smooth</code> with method <code>loess</code> to show a curve going through the points. You can change how adaptive the curve is to that through the <code>span</code> argument.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>popular_vote_filtered <span class="ot">&lt;-</span> popular_vote <span class="sc">|&gt;</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(start_date <span class="sc">&gt;=</span> <span class="fu">make_date</span>(<span class="dv">2024</span>, <span class="dv">7</span>, <span class="dv">21</span>) <span class="sc">&amp;</span> population <span class="sc">!=</span> <span class="st">"a"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(pollster) <span class="sc">|&gt;</span> </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pollster =</span> <span class="fu">ifelse</span>(<span class="fu">n</span>() <span class="sc">&lt;</span> <span class="dv">5</span>, <span class="st">"Other"</span>, pollster)) <span class="sc">|&gt;</span>  </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>popular_vote_filtered <span class="ot">&lt;-</span> popular_vote_filtered <span class="sc">|&gt;</span> </span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">start_date =</span> <span class="fu">as.Date</span>(start_date)) <span class="sc">|&gt;</span> </span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(start_date))</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>popular_vote_filtered <span class="ot">&lt;-</span> popular_vote_filtered <span class="sc">|&gt;</span> </span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(spread) <span class="sc">&amp;</span> <span class="fu">is.finite</span>(spread)) <span class="sc">|&gt;</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(spread <span class="sc">&gt;</span> <span class="sc">-</span><span class="dv">30</span> <span class="sc">&amp;</span> spread <span class="sc">&lt;</span> <span class="dv">30</span>)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(popular_vote_filtered <span class="sc">|&gt;</span> <span class="fu">filter</span>(population <span class="sc">==</span> <span class="st">"lv"</span>), </span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> start_date, <span class="at">y =</span> spread, <span class="at">color =</span> pollster)) <span class="sc">+</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>  </span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_date</span>(<span class="at">date_labels =</span> <span class="st">"%b %Y"</span>) <span class="sc">+</span>  </span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Popular Vote Trend for Likely Voters"</span>,</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Start Date"</span>, <span class="at">y =</span> <span class="st">"Spread (Harris - Trump)"</span>,</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Pollster"</span>) <span class="sc">+</span></span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pset-06-election_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(popular_vote_filtered <span class="sc">|&gt;</span> <span class="fu">filter</span>(population <span class="sc">==</span> <span class="st">"rv"</span>), </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> start_date, <span class="at">y =</span> spread, <span class="at">color =</span> pollster)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_date</span>(<span class="at">date_labels =</span> <span class="st">"%b %Y"</span>) <span class="sc">+</span>  </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Popular Vote Trend for Registered Voters"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Start Date"</span>, <span class="at">y =</span> <span class="st">"Spread (Harris - Trump)"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Pollster"</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pset-06-election_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="8" type="1">
<li>To show the pollster effect, make boxplots for the the spread for each popular vote poll. Include only likely voter polls starting after July 21, 2024. Rename all the pollsters with less than 5 polls during that time period as <code>Other</code>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for likely voter polls after July 21, 2024</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>popular_vote_filtered <span class="ot">&lt;-</span> popular_vote <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(start_date <span class="sc">&gt;</span> <span class="fu">make_date</span>(<span class="dv">2024</span>, <span class="dv">7</span>, <span class="dv">21</span>) <span class="sc">&amp;</span> population <span class="sc">==</span> <span class="st">"lv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(pollster) <span class="sc">%&gt;%</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n_pollster =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pollster =</span> <span class="fu">if_else</span>(n_pollster <span class="sc">&lt;</span> <span class="dv">5</span>, <span class="st">"Other"</span>, pollster))</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a boxplot for spread across different pollsters</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(popular_vote_filtered, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(pollster, spread, median), <span class="at">y =</span> spread <span class="sc">*</span> <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  <span class="co"># Add jittered points for better visibility</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Pollster Effect on Spread (Likely Voters)"</span>, </span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Pollster"</span>, </span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Spread (%)"</span>) <span class="sc">+</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()  <span class="co"># Flip axes for better readability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pset-06-election_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="9" type="1">
<li>Compute a prediction and an interval and report the result. Include the code you used to create your confidence interval for the popular vote here:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>lv_polls <span class="ot">&lt;-</span> popular_vote <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(start_date <span class="sc">&gt;</span> <span class="fu">make_date</span>(<span class="dv">2024</span>, <span class="dv">7</span>, <span class="dv">21</span>), population <span class="sc">==</span> <span class="st">"lv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(spread)  </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(lv_polls)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>prediction_popular <span class="ot">&lt;-</span> t_test_result<span class="sc">$</span>estimate <span class="sc">*</span> <span class="dv">100</span> </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>ci_popular <span class="ot">&lt;-</span> t_test_result<span class="sc">$</span>conf.int <span class="sc">*</span> <span class="dv">100</span>  </span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(prediction_popular)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mean of x 
 2.664364 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ci_popular)          </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.405065 2.923663
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
</div>
<p>Mean and Confidence Interval The sample mean of the spread, as estimated using a t-test, is 2.664%. This means that, among recent likely voter polls, the average spread between Harris and Trump is approximately 2.66 percentage points in favor of Harris.</p>
<p>The 95% confidence interval for this estimate is [2.41%, 2.92%]. This suggests that we are 95% confident that the true popular vote spread lies within this range.</p>
<p>Harris received a popular vote spread of <code>-1.5%</code> vs Trump in the 2024 election. How did your model do? Provide some potential explanations for the performance.</p>
<pre><code>In the 2024 election, Harris received an actual popular vote spread of -1.5% relative to Trump. Our model predicted a spread of +2.66% with a confidence interval of [2.41%, 2.92%], which does not include the actual result (-1.5%). This indicates that the model overestimated Harris’s performance by approximately 4.16 percentage points.
This significant overestimation of Harris's support could be attributed to several factors, including:Polling Bias; Turnout Differences; Weighting Issues.</code></pre>
<p>We now move on to predicting the electoral votes.</p>
<ol start="10" type="1">
<li>To obtain the number of electoral votes for each state we will visit this website:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://state.1keydata.com/state-electoral-votes.php"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can use the <strong>rvest</strong> package to download and extract the relevant table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">read_html</span>(url) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">html_table</span>() </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>ev <span class="ot">&lt;-</span> h[[<span class="dv">4</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wrangle the data in <code>ev</code> to only have two columns <code>state</code> and <code>electoral_votes</code>. Make sure the electoral vote column is numeric. Add the electoral votes for Maine CD-1 (1), Maine CD-2 (1), Nebraska CD-2 (1), and District of Columbia (3) by hand.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>url_ev <span class="ot">&lt;-</span> <span class="st">"https://state.1keydata.com/state-electoral-votes.php"</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">read_html</span>(url_ev) <span class="sc">%&gt;%</span> <span class="fu">html_table</span>()</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>ev <span class="ot">&lt;-</span> h[[<span class="dv">4</span>]] <span class="sc">%&gt;%</span> </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">state =</span> X2, <span class="at">electoral_votes =</span> X3) <span class="sc">%&gt;%</span>  </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(state, electoral_votes) <span class="sc">%&gt;%</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">electoral_votes =</span> <span class="fu">as.numeric</span>(electoral_votes)) <span class="sc">%&gt;%</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">state =</span> <span class="st">"Maine CD-1"</span>, <span class="at">electoral_votes =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">state =</span> <span class="st">"Maine CD-2"</span>, <span class="at">electoral_votes =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">state =</span> <span class="st">"Nebraska CD-2"</span>, <span class="at">electoral_votes =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">state =</span> <span class="st">"District of Columbia"</span>, <span class="at">electoral_votes =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `electoral_votes = as.numeric(electoral_votes)`.
Caused by warning:
! NAs introduced by coercion</code></pre>
</div>
</div>
<ol start="11" type="1">
<li>The presidential race in some states is a forgone conclusion. Because their is practically no uncertainty in who will win, polls are not taken. We will therefore assume that the party that won in 2020 will win again in 2024 if no polls are being collected for a state.</li>
</ol>
<p>Download the following sheet:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gsheet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gsheet' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>sheet_url <span class="ot">&lt;-</span> <span class="st">"https://docs.google.com/spreadsheets/d/1D-edaVHTnZNhVU840EPUhz3Cgd7m39Urx7HM8Pq6Pus/edit?gid=29622862"</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>raw_res_2020 <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(sheet_url) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tidy the <code>raw_res_2020</code> dataset so that you have two columns <code>state</code> and <code>party</code>, with <code>D</code> and <code>R</code> in the party column to indicate who won in 2020. Add Maine CD-1 (D), Maine CD-2 (R), Nebraska CD-2 (D), and District of Columbia (D) by hand. Save the result to <code>res_2020</code>. Hint use the <strong>janitor</strong> <code>row_to_names</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gsheet)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>sheet_url <span class="ot">&lt;-</span> <span class="st">"https://docs.google.com/spreadsheets/d/1D-edaVHTnZNhVU840EPUhz3Cgd7m39Urx7HM8Pq6Pus/edit?gid=29622862"</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>raw_res_2020 <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(sheet_url)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'janitor' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>raw_res_2020 <span class="ot">&lt;-</span> raw_res_2020 <span class="sc">%&gt;%</span> <span class="fu">row_to_names</span>(<span class="at">row_number =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Row 1 does not provide unique names. Consider running clean_names()
after row_to_names().</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>raw_res_2020 <span class="ot">&lt;-</span> raw_res_2020 <span class="sc">%&gt;%</span> <span class="fu">clean_names</span>()</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>res_2020 <span class="ot">&lt;-</span> raw_res_2020 <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(state, biden_joe_democratic, trump_donald_republican) <span class="sc">%&gt;%</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">biden =</span> <span class="fu">as.numeric</span>(biden_joe_democratic),</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">trump =</span> <span class="fu">as.numeric</span>(trump_donald_republican),</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">party =</span> <span class="fu">if_else</span>(biden <span class="sc">&gt;</span> trump, <span class="st">"D"</span>, <span class="st">"R"</span>)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(state, party)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>res_2020 <span class="ot">&lt;-</span> res_2020 <span class="sc">%&gt;%</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">state =</span> <span class="st">"Maine CD-1"</span>, <span class="at">party =</span> <span class="st">"D"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">state =</span> <span class="st">"Maine CD-2"</span>, <span class="at">party =</span> <span class="st">"R"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">state =</span> <span class="st">"Nebraska CD-2"</span>, <span class="at">party =</span> <span class="st">"D"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">state =</span> <span class="st">"District of Columbia"</span>, <span class="at">party =</span> <span class="st">"D"</span>)</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(res_2020)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 62 × 2
   state       party
   &lt;chr&gt;       &lt;chr&gt;
 1 Nationwide  D    
 2 Alabama     R    
 3 Alaska      R    
 4 Arizona     D    
 5 Arkansas    R    
 6 California  D    
 7 Colorado    D    
 8 Connecticut D    
 9 Delaware    D    
10 Florida     R    
# ℹ 52 more rows</code></pre>
</div>
</div>
<ol start="12" type="1">
<li>Decide on a period that you will use to compute your prediction. We will use <code>spread</code> as the outcome. Make sure the the outcomes is saved as a proportion not percentage. Create a <code>results</code> data frame with columns <code>state</code>, <code>avg</code>, <code>sd</code>, <code>n</code> and <code>electoral_votes</code>, with one row per state.</li>
</ol>
<p>Some ideas and recommendations:</p>
<ul>
<li>If a state has enough polls, consider a short period, such as a week. For states with few polls you might need to increase the interval to increase the number of polls.</li>
<li>Decide which polls to prioritize based on the <code>population</code> and <code>numeric_grade</code> columns.</li>
<li>You might want to weigh them differently, in which you might also consider using <code>sample_size</code>.</li>
<li>If you use fewer than 5 polls to calculate an average, your estimate of the standard deviation (SD) may be unreliable. With only one poll, you wont be able to estimate the SD at all. In these cases, consider using the SD from similar states to avoid unusual or inaccurate estimates.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> polls <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(start_date <span class="sc">&gt;</span> <span class="fu">make_date</span>(<span class="dv">2024</span>, <span class="dv">7</span>, <span class="dv">21</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg =</span> <span class="fu">mean</span>(spread),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">if_else</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>, <span class="fu">sd</span>(spread), <span class="cn">NA_real_</span>),</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(ev, <span class="at">by =</span> <span class="st">"state"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="13" type="1">
<li>Note you will not have polls for all states. Assume that lack of polls implies the state is not in play. Use the <code>res_2020</code> data frame to compute the electoral votes Harris is practically guaranteed to have.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>harris_start <span class="ot">&lt;-</span> res_2020 <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(party <span class="sc">==</span> <span class="st">"D"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(ev, <span class="at">by =</span> <span class="st">"state"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">sum</span>(electoral_votes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(total)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(harris_start)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 305</code></pre>
</div>
</div>
<ol start="14" type="1">
<li>Use a Bayesian approach to compute posterior means and standard deviations for each state in <code>results</code>. Plot the posterior mean versus the observed average with the size of the point proportional to the number of polls.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>prior_mean <span class="ot">&lt;-</span> <span class="fu">median</span>(results<span class="sc">$</span>avg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>prior_n <span class="ot">&lt;-</span> <span class="dv">5</span>  </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">posterior_mean =</span> (n <span class="sc">*</span> avg <span class="sc">+</span> prior_n <span class="sc">*</span> prior_mean) <span class="sc">/</span> (n <span class="sc">+</span> prior_n))  </span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(results, <span class="fu">aes</span>(<span class="at">x =</span> avg <span class="sc">*</span> <span class="dv">100</span>, <span class="at">y =</span> posterior_mean <span class="sc">*</span> <span class="dv">100</span>, <span class="at">size =</span> n)) <span class="sc">+</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span>  <span class="co"># 添加散点图</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Posterior Mean vs Observed Average (State-Level)"</span>,</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Observed Average Spread (%)"</span>,</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Posterior Mean Spread (%)"</span>,</span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">size =</span> <span class="st">"Number of Polls"</span>) <span class="sc">+</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pset-06-election_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="15" type="1">
<li>Compute a prediction and an interval for Harris’ electoral votes and show the result. Include the code you used to create your estimate and interval below.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predicted_win =</span> <span class="fu">if_else</span>(posterior_mean <span class="sc">&gt;</span> <span class="dv">0</span>, electoral_votes, <span class="dv">0</span>))</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>predicted_ev <span class="ot">&lt;-</span> <span class="fu">sum</span>(results<span class="sc">$</span>predicted_win, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">var =</span> <span class="fu">if_else</span>(<span class="sc">!</span><span class="fu">is.na</span>(sd) <span class="sc">&amp;</span> n <span class="sc">&gt;</span> <span class="dv">1</span>, (sd<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n, <span class="dv">0</span>))</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>total_variance <span class="ot">&lt;-</span> <span class="fu">sum</span>(results<span class="sc">$</span>var, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>se_total <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(total_variance)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% Confidence interval</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>ci_ev <span class="ot">&lt;-</span> <span class="fu">c</span>(predicted_ev <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_total, predicted_ev <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_total)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Predicted Electoral Votes for Harris:"</span>, <span class="fu">round</span>(predicted_ev), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Electoral Votes for Harris: 264 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>ci_ev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 263.7479 264.2521</code></pre>
</div>
</div>
<p>Harris received 226 electoral votes in the 2024 election. How did your model do? Provide some potential explanations for the performance.</p>
<pre><code>My model predicted that Harris would receive 264 electoral votes with a 95% confidence interval of [263.75, 264.25], but the actual result was only 226 votes, suggesting that the model overestimated Harris' support.
The reasons for this could be 1. My prediction is based on recent polling data, which may be systematically biased. For example, voters failed to vote according to polling preferences (e.g., swing voters ultimately chose Trump).
2. Voter turnout misjudgement: my model does not take into account the effect of actual voter turnout.
3. The model assumptions may be overly optimistic; my model uses Bayesian adjustment to calculate the posterior mean, but may not adequately account for election uncertainty.
</code></pre>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>